- role: External Reviewer
  organization: International Symposium on High-Performance Computer Architecture (HPCA)
  period: 2024

- role: Technical Program Committee
  organization: Design Automation Conference
  period: 2023

- role: Reviewer
  organization: IEEE Computer Architecture Letters (IEEE CAL)
  period: 2023

- role: Reviewer
  organization: ACM Transactions on Embedded Computing Systems (IEEE TECS)
  period: 2023
  
- role: Reviewer
  organization: IEEE Transactions on Cloud Computing (IEEE TCC)
  period: 2023

- role: Reviewer
  organization: IEEE Transactions on Computers (IEEE TC)
  period: 2023, 2020, 2019

- role: Reviewer
  organization: IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems (IEEE TCAD)
  period: 2022, 2021, 2017

- role: External Reviewer
  organization: European Conference on Computer Systems (EuroSys)
  period: 2022

- role: Reviewer
  organization: ACM Transactions on Architecture and Code Optimization (ACM TACO)
  period: 2020

- role: Reviewer
  organization: ACM Computing Surveys (ACM CSUR)
  period: 2020
