menu:
#- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

#courses:
#- {name: 'Vector Calculus', url: 'vector-calculus'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
#- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/jisung-park'}
#- {icon: 'facebook', link: 'https://facebook.com/jisungpark.phd'}
- {icon: 'twitter', link: 'https://twitter.com/jspark_phd'}
- {icon: 'instagram', link: 'https://instagram.com/jspark.phd'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/jisung-park'}

contacts:
- {name: 'Dr. Jisung Park', title: 'Assistant Professor', department: 'Computer Science and Engineering', institution: 'POSTECH', institution_address: '77, Cheongam-ro, Nam-gu, Pohang-si, Gyeongsangbuk-do, Republic of Korea 37673', phone: '+82-54-279-2263', email: 'jisungpark@postech.ac.kr', office: 'B4 125-2', image: 'assets/img/contact.jpg'}
