menu:
- {name: 'Publications', url: '/publications'}
#- {name: 'CV', url: '/cv'}
#- {name: 'people', url: '/people'}
#- {name: 'courses', url: '/courses'}

students:
  - id: gildong.hong
    name: Gildong Hong
    email: gdhong@email.com
    status: present
    role: Ph.D. Student
    webpage: gdhong.github.io

courses:
  - id: CSED702A-01
    name: Memory and Storage Systems
    url: 'memory-and-storage-systems'

social:
- {icon: 'github', link: 'https://github.com/jisung-park'}
- {icon: 'facebook', link: 'https://facebook.com/jisungpark.phd'}
- {icon: 'twitter', link: 'https://twitter.com/jspark_phd'}
- {icon: 'instagram', link: 'https://instagram.com/jspark.phd'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/jisung-park'}

institution_address: '77, Cheongam-ro, Nam-gu, Pohang-si, Gyeongsangbuk-do, Republic of Korea 37673'
phone: '+82-54-279-2263'
email: 'jisungpark@postech.ac.kr'
office: 'B4 125-2'
image: 'assets/img/contact.jpg'
dblp_id: '2642-1'
scholar: '1qw7AosAAAA'
